language: node_js
node_js:
  - "8.6.0"
  - "node"
env:
  - WEBPACK_VERSION= # Current, from package.json
  - WEBPACK_VERSION=4
install:
  # Use npm 5.7.x since it has introduced `npm ci`
  - if [[ `npm -v` != 5.7* ]]; then npm install -g npm@'>=5.7.1'; fi
  - npm ci
before_script:
  # Install Webpack version
  - if [[ -n "$WEBPACK_VERSION" ]]; then npm install --no-save webpack@$WEBPACK_VERSION; fi
branches:
  except:
    - gh-pages
stages:
  - build
jobs:
  include:
    - stage: build
      script: 
        # Run build
        - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: '/dist/'
  on:
    branch: master
